version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.15.0-browse
    steps:
      - run: node --version      
      - checkout
      - run: yarn 
      - run: yarn build
      - run: yarn run start