version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "16.13.1-browsers"
      - node/install-packages
      - run:
          command: yarn 
      - run:
          command: yarn run start

workflows:
  build-and-test:
    jobs:
      - build-and-test