version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - docker/check:
          docker-username: jerryliu  # DOCKER_LOGIN is the default value, if it exists, it automatically would be used.
          docker-password: moly2002       
      - checkout
      - node/install:
          node-version: "16.13.1-browsers"
      - node/install-packages
      - run:
          command: yarn 
      - run:
          command: yarn run start

workflows:
  build-and-test:
    jobs:
      - build-and-test